USE_CAMERA_STUB := false

TARGET_SPECIFIC_HEADER_PATH := device/huawei/G300/include
TARGET_OTA_ASSERT_DEVICE := G300,U8815,u8815,hwu8815

#Board Settings
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7x27a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_BOOTLOADER_BOARD_NAME := G300
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp -march=armv7-a 
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp -march=armv7-a
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
BOARD_USES_ADRENO_200 := true
#TARGET_USES_ION := true
TARGET_PROVIDES_INIT_RC := true
TARGET_PROVIDES_RECOVERY_INIT_RC := true
TARGET_RECOVERY_INITRC := device/huawei/G300/init.rc
TARGET_CPU_SMP := true

TARGET_CORTEX_CACHE_LINE_32 := true
TARGET_USE_SPARROW_BIONIC_OPTIMIZATION := true
#BOARD_USES_SRS_TRUEMEDIA := true 
 

# QCOM hardware
BOARD_USES_QCOM_HARDWARE := true
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE

#    TARGET_HAS_S3D_SUPPORT := true
   WEBCORE_INPAGE_VIDEO := true
TARGET_HAVE_TSLIB := false

# Camera
COMMON_GLOBAL_CFLAGS += -DICS_CAMERA_BLOB
BOARD_NEEDS_MEMORYHEAPPMEM := true


#Graphics
BOARD_EGL_CFG := device/huawei/G300/proprietary/lib/egl/egl.cfg
USE_OPENGL_RENDERER := true
COMMON_GLOBAL_CFLAGS += -DFORCE_CPU_UPLOAD 
COMMON_GLOBAL_CFLAGS += -DQCOM_NO_SECURE_PLAYBACK -DQCOM_LEGACY_OMX -DQCOM_ICS_COMPAT -DQCOM_NO_DMX_SUPPORT -DQCOM_ROTATOR_KERNEL_FORMATS
TARGET_GRALLOC_USES_ASHMEM := true
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
BOARD_USES_16BPPSURFACE_FOR_OPAQUE := true
TARGET_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true

#Browser
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true
#DYNAMIC_SHARED_LIBV8SO := true
WITH_JIT := true
ENABLE_JSC_JIT := true
JS_ENGINE := v8


#GPS
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := default

# Audio
BOARD_HAVE_QCOM_FM := true
COMMON_GLOBAL_CFLAGS += -DWITH_QCOM_FM -DQCOM_FM_ENABLED -DQCOM_VOIP_ENABLED 
TARGET_PROVIDES_LIBAUDIO := true

# Wi-Fi
BOARD_HAVE_HUAWEI_WIFI := true
WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WLAN_DEVICE           := bcmdhd
WIFI_DRIVER_MODULE_PATH     := "/system/lib/modules/dhd_4330.ko"
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER        := NL80211
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_bcmdhd
WIFI_DRIVER_MODULE_NAME := "dhd_4330"
BOARD_LEGACY_NL80211_STA_EVENTS := true
WIFI_DRIVER_FW_PATH_STA := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_FW_PATH_P2P := "/system/wifi/fw_4330_b2_p2p.bin"
WIFI_DRIVER_FW_PATH_AP := "/system/wifi/fw_4330_b2_apsta.bin"
WIFI_DRIVER_FW_PATH_PARAM := "/sys/module/dhd_4330/parameters/firmware_path"
WIFI_DRIVER_MODULE_ARG := "firmware_path=/system/wifi/fw_4330_b2.bin nvram_path=/system/wifi/nvram_4330.txt"
WIFI_BAND                        := 802_11_ABG

PRODUCT_WIRELESS_TOOLS := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true


#RIL
#BOARD_USES_HC_RADIO := true
#BOARD_PROVIDES_LIBRIL := true

#Sensors
TARGET_PROVIDES_LIBLIGHTS :=true


# Bootanimation
TARGET_BOOTANIMATION_PRELOAD := true

BOARD_KERNEL_CMDLINE := console=ttyDCC0 androidboot.hardware=huawei
BOARD_KERNEL_BASE := 0x00200000
BOARD_PAGE_SIZE := 2048


BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00C00000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00C00000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_FLASH_BLOCK_SIZE := 0x00020000
TARGET_USERIMAGES_USE_EXT4 := true

BOARD_HAS_NO_MISC_PARTITION := true

TARGET_KERNEL_CUSTOM_TOOLCHAIN := arm-eabi-4.4.3
TARGET_KERNEL_SOURCE := kernel/huawei/kernel
TARGET_KERNEL_CONFIG := g300_jb_defconfig

BOARD_HAS_NO_SELECT_BUTTON := true
# Use this flag if the board has a ext4 partition larger than 2gb
BOARD_HAS_LARGE_FILESYSTEM := true

# SD Card
BOARD_HAS_SDCARD_INTERNAL := true
BOARD_SDEXT_DEVICE := /dev/block/mmcblk1p1
BOARD_USES_MMCUTILS := true

# Insecure boot
ADDITIONAL_DEFAULT_PROPERTIES += ro.secure=0
ADDITIONAL_DEFAULT_PROPERTIES += persist.service.adb.enable=1


BOARD_VOLD_MAX_PARTITIONS :=30
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/class/android_usb/android0/f_mass_storage/lun%d/file"
BOARD_UMS_LUNFILE := "/sys/class/android_usb/android0/f_mass_storage/lun%d/file"

TARGET_RECOVERY_GUI := true
DEVICE_RESOLUTION := 480x800
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/sdcard-ext"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard-ext"
TW_FLASH_FROM_STORAGE := true 
#TW_DEFAULT_EXTERNAL_STORAGE := true
#RECOVERY_SDCARD_ON_DATA := true
#TW_NO_USB_STORAGE := true
BOARD_HAS_NO_REAL_SDCARD := true
#TW_NO_REBOOT_BOOTLOADER := true 
#TW_NEVER_UNMOUNT_SYSTEM := false
#TW_INCLUDE_INJECTTWRP := false
#TW_ALWAYS_RMRF := false

SP1_NAME := "cust"
SP1_DISPLAY_NAME := "cust"
SP1_BACKUP_METHOD := image
SP1_MOUNTABLE := 1
SP2_NAME := "sdcard"
SP2_BACKUP_METHOD := files
SP2_MOUNTABLE := 1
#SP3_NAME := "aboot"
#SP3_DISPLAY_NAME := "Appsboot"
#SP3_BACKUP_METHOD := image
#SP3_MOUNTABLE := 1
